name: Bazaar
version: '${project.version}'
main: dev.ked.bazaar.BazaarPlugin
api-version: '1.21'
description: Intuitive player-to-player shop system with GUI and holograms
author: Kyle Donaldson
website: https://ked.dev

depend:
  - Vault

softdepend:
  - PlaceholderAPI
  - Towny
  - TownsAndNations
  - SilkRoad

commands:
  shop:
    description: Main shop command
    usage: /<command> [create|remove|info|collect|list|reload|silkroad]
    aliases: [bshop, playershop, bazaar]
    permission: bazaar.use

permissions:
  bazaar.use:
    description: Allows basic shop usage
    default: true
  bazaar.create:
    description: Allows creating shops
    default: true
  bazaar.remove:
    description: Allows removing own shops
    default: true
  bazaar.info:
    description: Allows viewing shop info
    default: true
  bazaar.list:
    description: Allows listing own shops
    default: true
  bazaar.silkroad:
    description: Allows enabling/disabling Silk Road for shops
    default: true
  bazaar.admin:
    description: All admin permissions
    default: op
    children:
      bazaar.admin.reload: true
      bazaar.admin.remove: true
      bazaar.silkroad: true
  bazaar.admin.reload:
    description: Reload plugin configuration
    default: op
  bazaar.admin.remove:
    description: Remove any shop
    default: op